export declare const HEADER_NO_ESLINT = "/* eslint-disable */";
export declare const HEADER_WARNING = "/* DO NOT EDIT THIS FILE OR YOU WILL BE FIRED. Or not, I dunno... */";
export declare const HEADER_AUTO_GENERATED = "/* This file was automatically generated by \"re-i18n\" */";
//# sourceMappingURL=constants.d.ts.map