export const HEADER_NO_ESLINT = "/* eslint-disable */";
export const HEADER_WARNING = "/* DO NOT EDIT THIS FILE OR YOU WILL BE FIRED. Or not, I dunno... */";
export const HEADER_AUTO_GENERATED = '/* This file was automatically generated by "re-i18n" */';
//# sourceMappingURL=constants.js.map