import nunjucks from "nunjucks";

import type { I18nTemplateData } from "../schemas/template";

const template = `/* eslint-disable */
// This file is generated by re-i18n, do not edit
{% if formatterPath -%}
import { createI18n, type I18nLangSet } from "re-i18n";

import formatter from "{{ formatterPath }}";
{% else -%}
import { createI18n, formatter, type I18nLangSet } from "re-i18n";
{% endif -%}
import getLang from "{{ getLangPath }}";

{% for lang in langs -%}
import {{ lang }} from "./{{ lang }}.json";
{% endfor %}
type I18nKey = {% for lang in langs %}keyof typeof {{lang}}{% if not loop.last %} & {% endif %}{% endfor %};
type I18nLang = {% for lang in langs %}"{{lang}}"{% if not loop.last %} | {% endif %}{% endfor %};

const langSet: I18nLangSet<I18nLang, I18nKey> = {
{% for lang in langs %}  {{ lang -}},
{% endfor -%}
};

export const {{ funcName }} = createI18n<I18nLang, I18nKey>(langSet, formatter, getLang);
`;

export function render(data: I18nTemplateData) {
  return nunjucks.renderString(template, data);
}
