/* eslint-disable */
/* DO NOT EDIT THIS FILE OR YOU WILL BE FIRED. Or not, I dunno... */
/* This file was automatically generated by "re-i18n" */
import { createI18n, type I18nLocales } from "re-i18n";

import formatter from "../../../../i18n/formatter";
import getLocale from "../../../../i18n/getLang";

import ja from "./ja.json";
import en from "./en.json";

type I18nKey = keyof typeof ja & keyof typeof en;

const locales: I18nLocales<I18nKey> = {
  ja,
  en,
};

export const t = createI18n<I18nKey>(locales, formatter, getLocale);
