name: Test and Lint Example Project

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint:
    name: Test and Lint Example Project
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies and build re-i18n
      run: npm ci && npm run build

    - name: Install dependencies for example
      run: npm ci --prefix example

    - name: Run type check
      run: npm run type-check --prefix example

    - name: Run i18n:lint
      run: npm run i18n:lint --prefix example
